CREATE TABLE roles (
	id SERIAL PRIMARY KEY,
	name VARCHAR(15) UNIQUE NOT NULL
);

INSERT INTO roles(name)
VALUES
('HR'),('MANAGER'),('EMPLOYEE');

CREATE TABLE users (
	id BIGSERIAL PRIMARY KEY,
	first_name VARCHAR(15) NOT NULL,
	last_name VARCHAR(15) NOT NULL,
	email VARCHAR(70) UNIQUE NOT NULL,
	password VARCHAR(255) NOT NULL,
	phone VARCHAR(15),
	active BOOLEAN DEFAULT TRUE,
	role_id INT NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

	CONSTRAINT fk_user_role
	FOREIGN KEY(role_id)
	REFERENCES roles(id)	
);